### ISSUE TITLE
conda conflicts

### ISSUE THREAD

**Issue by HamLaertes** [Thartvigsen/GRACE#2]
Hi, when running the conda command in the README
`
conda env create --name grace_env --file environment.yml,
`
my conda failed to create the enviroment because of encountering amounts of conflicts. It is too long to be pasted here.

It seems to come from other problem rather than simple conflicts (for it is too many), such as the conda version or others.
Can you help me about this?

**Comment by Thartvigsen** [comment]
Thanks for pointing this out, I'm looking into it. For now, this repository should not be very brittle to package versions, so you might run the code and install required packages as you go! I will close this issue when I've uploaded a new environment file.

**Comment by Thartvigsen** [comment]
@HamLaertes, please try again using the [new environment file](https://github.com/Thartvigsen/GRACE/tree/main#:~:text=last%20month-,environment.yml,-Simplified%20environment.yml).
