### ISSUE TITLE
'GRACEAdaptor' object has no attribute 'weight' when running examples.ipynb

### ISSUE THREAD

**Issue by TonAnh** [Thartvigsen/GRACE#3]
Hi, I currently trying to rerun your repo. I clone the repo and then run the examples.ipynb but this cell

`# --- wrap model with GRACE ---
edited_model = GRACE(model, layer_to_edit, init_epsilon, learning_rate, device, generation=False)`

Return the error 'GRACEAdaptor' object has no attribute 'weight'. I haven't edited anything in the repo yet. Could you help me, please?

**Comment by Thartvigsen** [comment]
Hi @TonAnh, thanks for bringing this up. This is a known error that I haven't been able to reproduce on my end... could you confirm you're using a conda environment set up from environment.yml?

**Comment by TonAnh** [comment]
@Thartvigsen Hi, thanks for your response.

Yes, I have followed the setup steps. The difference may be that I rent the GPU from VastAI so I don't know if there is any impact on the process of choosing to use PyTorch templates from VastAI?

**Comment by Thartvigsen** [comment]
I doubt that's the problem but I will investigate, thanks for bringing this to my attention, I will get back to you!

**Comment by Thartvigsen** [comment]
@TonAnh I've added a patch fix, please let me know if it works for you? I still need to dig into why this isn't a reproducible bug on my end, but I added `self.weight = self.layer.weight` inside GRACEAdaptor per the suggestion from the repeated issue: https://github.com/Thartvigsen/GRACE/issues/1

Please let me know if this works or doesn't work!

**Comment by TonAnh** [comment]
@Thartvigsen Hi, sorry for the late reply, I missed the notification from my email. I have tried again and everything works great now. Thank you very much.

**Comment by Thartvigsen** [comment]
glad to hear it!
