### ISSUE TITLE
About experiments on ROME

### ISSUE THREAD

**Issue by littlefive5** [Thartvigsen/GRACE#4]
I found the repo didn't show the code for running the ROME method and I'm curious about the implementation for ROME on the Hallucination tasks.
ROME is designed for the fact edit and the target is the object entity o^*. For the hallucination task, is the new o^* the whole new sentence? 
Besides, when conducting the ROME on Hallucination, how to get the new v^* and the new k^*?
![image](https://github.com/Thartvigsen/GRACE/assets/36941249/0198657a-446e-4dde-9dbe-fc6613db4c93)

**Comment by Thartvigsen** [comment]
Thanks for your interest in our work! We're working to release the codebase soon. Per the [apply_rome_to_model](https://github.com/kmeng01/memit/blob/main/rome/rome_main.py) function, in their `requests` format, we set the `prompt` to `This is a Wikipedia passage about {}. + [insert the sentence(s) before the edit]` . Then we set the `subject` to the subject of the wikipedia article (which is extra exogenous data w.r.t. our setup) and `target_new` to be the output sentence we'd like the model to produce.
