### ISSUE TITLE
Expected input batch_size (13) to match target batch_size (2)

### ISSUE THREAD

**Issue by XeeKee** [Thartvigsen/GRACE#6]
my setting:experiment=qa model=gpt2xl editor=grace

Looking forward to your reply

**Comment by XeeKee** [comment]
![WechatIMG83](https://github.com/Thartvigsen/GRACE/assets/70566607/a0e8e29d-cbeb-4626-aff5-3b155755cb30)
my tokens is as follows
![WechatIMG84](https://github.com/Thartvigsen/GRACE/assets/70566607/21d60536-75bb-4b0a-8d93-5bdfdeefdf73)

**Comment by Thartvigsen** [comment]
Thanks for your comment. The current implementation does not support using gpt2xl for qa experiments. You would need to edit the T5 model for QA or edit the gpt2xl model for Hallucination.
